# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='img_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
