# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20171030_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='img_url',
            field=models.CharField(max_length=100),
        ),
    ]
